#!/bin/bash
# Google Drive folder IDs for Knowledge Base
# Generated: 2026-03-11

# Root folder
KB_ROOT_ID="18RkzPrRMXkpBseUuSNPiOLx-HIr-cM0o"

# PARA folders
INBOX_ID="1XwPHpsRiJNCCaoj8H6FT6ucLHJO6NS38"
PROJECTS_ID="19U_K5Zfcxhhlt8Tsafe5hmJzB9XdYkus"
AREAS_ID="1CZDwyRchscBDXNvOT0l6huxyeotG4S48"
RESOURCES_ID="1Pp8pisGAjOhmF5dryMhySxZ-TgbpxoCG"
ARCHIVE_ID="1o0A3x8Czdsv14E8F2oVmoAd5m7GGsIMH"
SYSTEM_ID="1tYELOJpZdOrPMQ-2eOEHRG2lk6Tf-T9T"
TEMPLATES_ID="1Gb0yt3RrnvCziT7AnkAl4ZcciU_eApnh"

# Master Index spreadsheet
INDEX_SHEET_ID="1KEkuPlvrvx16Q5knTFRaNY3ij77vvuUvyX4U5J6dtis"

# Document templates
PROJECT_TEMPLATE_ID="1jLkFBLACaVuPKtouX28sbOPfp3pt8l81PCMZ7XG5Q8s"
AREA_TEMPLATE_ID="1IT4Z8_CXclDOgErJTcT0xi-evISDAbKmKdBGPxt0CgM"
RESOURCE_TEMPLATE_ID="1I2fvys5fI9_Bh2WZAkf16d4uF7YQCCDnYj59eRWbG2g"

# Area subfolders
AREA_CAREER_ID="1tNeC0GpkdFs1oLSMJ_wEXyVZX9Lqep7O"
AREA_FINANCES_ID="1vqZ4xrgwaHOcW3iWX3p3djIFpRyyzjEO"
AREA_HEALTH_ID="10l8qNkebw_YnbOsfuXx1ClkhjAW2tm7L"
AREA_LEARNING_ID="1U6AWeQZY3nEgVKYcIHlqrHZTKOV_sAoE"
AREA_PERSONAL_GROWTH_ID="1hlI7bUSTJDhRT-gCAMZL5OaR1moW9dPI"
AREA_RELATIONSHIPS_ID="1ggpSz-A85D6Vitkykh_jezxFSyY-j8f-"

# Resource subfolders
RESOURCE_AI_TOOLS_ID="1eYjcCFvfdncHtxtmk_Ng1wb40yNI2pyf"
RESOURCE_CODING_ID="1BpjKxuXSmFvw8nZFcg7ir87dnbUViFGL"
RESOURCE_ENTREPRENEURSHIP_ID="1S5vev2zu2ZVPaIJrfLToYrkzN6QUtGUK"
RESOURCE_KNOWLEDGE_MANAGEMENT_ID="1CX4q1KTaYWSmOWaVP3Mfc_FGhejTq-GE"
RESOURCE_NEURODIVERSITY_ID="1i2BfA0na_DTV6L4ygARrS0f2MQYz5TlJ"
RESOURCE_PRODUCTIVITY_ID="19487otV2dy5RjLeClSXrs0exy3ByZZ9n"

# Gmail labels
GMAIL_LABEL_PROJECTS="Label_12"
GMAIL_LABEL_AREAS="Label_13"
GMAIL_LABEL_RESOURCES="Label_14"
GMAIL_LABEL_ARCHIVE="Label_15"
GMAIL_LABEL_AI_DIGEST="Label_16"
